version: "3.9"

services:
  web:
    build:
      context: .
      dockerfile: ./Containerfile
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
    volumes:
      - ./:/var/www/html:z
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
    restart: always
    volumes:
      - ./:/var/www/html:z
      - ./nginx-config.conf:/etc/nginx/conf.d/default.conf:z
    depends_on:
      - web
    networks:
      - app-network

  db:
    image: postgres:17
    restart: always
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data:z
      - ./postgres:/docker-entrypoint-initdb.d:z
    networks:
      - app-network

networks:
  app-network:

volumes:
  db_data:
